# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:title.html 

exclude: ["todo.md"]
highlighter: pygments

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Fundamentals of Interactive
tagline: Data Module Fall 2014

author :
  name    : Amanda Hickman
  email   : amanda.hickman@journalism.cuny.edu
  github  : amandabee
  twitter : amandabee
course :   
  semester: Fall 2014
  title   : Fundamentals of Interactive Data Module

JB :
  version : 0.3.0

BASE_PATH : /fundamentals-of-interactive
ASSET_PATH : /fundamentals-of-interactive/assets

baseurl : /fundamentals-of-interactive
 
