# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

exclude: ["todo.md"]
highlighter: pygments

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Fundamentals of Interactive
tagline: Fundamentals of Interactive, Fall 2014
author :
  name : Amanda Hickman
  email : amanda.hickman@journalism.cuny.edu
  github : amandabee
  twitter : amandabee

JB :
  version : 0.3.0

BASE_PATH : http://amandabee.github.io/fundamentals-of-interactive
ASSET_PATH : false

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
atom_path : /atom.xml
rss_path : /rss.xml
 
